spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:conferencedb
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    
